### ISSUE TITLE
MonerisGateway Lookup Masked Card

### ISSUE THREAD

**Issue by tzumby** [Shopify/active_merchant#1639]
Hi guys,

I wanted to bring this new functionality in an issue before doing any work on my fork and sending a pull request. This is the API call in question:

res_lookup_masked
This call takes a credit card token and returns a the first 4 and last 4 digits. 

I know you guys are skeptical about adding new methods to the gateway class (and for good reasons) but I can't find any existing ones that could accommodate this one. Maybe one of you worked on something similar for other gateways and could share some insight (This would basically be card retrieval) ?

Cheers,

-Razvan

**Comment by ntalbott** [comment]
@tzumby ActiveMerchant's not a good fit for card retrieval; I'd recommend just integrating directly to the Moneris API for this functionality.

**Comment by tzumby** [comment]
I understand you want to keep the library lean, but what would be the point of using ActiveMerchant for the transactions and then creating another wrapper just for the other functions ?

**Comment by ntalbott** [comment]
@tzumby ActiveMerchant is targeted at being an abstraction across multiple gateways, and we haven't found a useful abstraction (nor, honestly, do the maintainers need an abstraction) across card retrieval, since it's so gateway specific. If you're only using Moneris, the benefits of using ActiveMerchant vs a gateway-specific library are limited.

Of course, you always have the option of just mixing your own method(s) into the adapter in your own code. If the AM connection code, response handling, etc., is useful to you, could totally make sense to use the adapter and tack the extra functionality on yourself. It's just not something we think fits for the underlying project/gem.

**Comment by tzumby** [comment]
That's a fair point. Your comment about mixing in the response handling and connection code makes me think of @alovak's suggestion about extracting gateways into their own separate gems.
